DELETE http://localhost:3001/api/persons/604d3bdb05102729e06d8825

###
GET  http://localhost:3001/api/persons

###

GET  http://localhost:3001/info

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jan Duda",
    "number": "12345678910"
}

###
PUT http://localhost:3001/api/persons/60411a108da6004eac604276
Content-Type: application/json

{
    "name": "Jan Andrzej Duda",
    "number": "123123123111"
}